# Generated by Django 3.1.2 on 2020-12-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=50)),
                ('lang', models.CharField(max_length=15)),
                ('body', models.TextField()),
            ],
        ),
    ]
