# Generated by Django 3.1.2 on 2020-12-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustore', '0002_auto_20201205_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=15)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
